[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

;upload_port = /dev/cu.wchusbserial5A7B0732241
;upload_port = /dev/cu.wchusbserial5A7B0732301

upload_port = /dev/cu.wchusbserial5A7B0732261

monitor_port = /dev/cu.wchusbserial5A7B0732261

;monitor_port = /dev/cu.wchusbserial5A7B0732241
;monitor_port = /dev/cu.wchusbserial5A7B0732301

lib_deps =
    adafruit/Adafruit NeoPixel

upload_speed = 460800
monitor_speed = 115200

upload_protocol = esptool

; CH343P-safe monitor settings
monitor_dtr = 0
monitor_rts = 0

; Most compatible flash mode for mixed-batch C3 boards
board_build.flash_mode = dio
